<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">    
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="../../favicon.ico">

        <title>Controle Puxada</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <?=
                $this->headStyle()
                ->appendStyle('body{padding-top:40px;padding-bottom:40px;background-color:#eee}'
                        . '.form-signin{max-width:330px;padding:15px;margin:0 auto}.form-signin '
                        . '.checkbox,.form-signin .form-signin-heading{margin-bottom:10px}'
                        . '.form-signin .checkbox{font-weight:400}.form-signin '
                        . '.form-control{position:relative;height:auto;-webkit-box-sizing:border-box;'
                        . '-moz-box-sizing:border-box;box-sizing:border-box;padding:10px;'
                        . 'font-size:16px}.form-signin .form-control:focus{z-index:2}'
                        . '.form-signin input[type=email]{margin-bottom:-1px;'
                        . 'border-bottom-right-radius:0;border-bottom-left-radius:0}'
                        . '.form-signin input[type=password]{margin-bottom:10px;'
                        . 'border-top-left-radius:0;border-top-right-radius:0}')
        ?>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>

        <div class="container">
            <?php
            if (isset($this->erros)) {
                foreach ($this->erros as $erro) {
                    ?>
                    <div class="alert alert-danger">
                        <?= $erro ?>
                    </div>
                    <?php
                }
            }
            $form->prepare();
            echo $this->form()->openTag($form);
            $elements = $this->form->getElements();
            ?>
            <h2 class="form-signin-heading">Efetuar Login</h2>
            <?php
            echo $this->formElement($elements['login']);
            echo $this->formElementErrors($elements['login']);
            echo $this->formElement($elements['senha']);
            echo $this->formElementErrors($elements['senha']);
            echo $this->formElement($elements['submit']);
            echo $this->form()->closeTag();
            ?>
        </div> <!-- /container -->
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>
</html>
